-- AgentAtlas — full Supabase bootstrap
-- Run this once in your Supabase SQL editor to create all required tables.
-- Safe to re-run (uses IF NOT EXISTS throughout).

-- ── validation_runs ────────────────────────────────────────────────────────
create table if not exists public.validation_runs (
    id                  bigint generated by default as identity primary key,
    playbook_id         text,
    site_id             text,
    route_id            text,
    task_id             text,
    variant_key         text,
    validated_at        timestamptz not null default timezone('utc', now()),
    status              text,
    success_rate        double precision,
    success_count       integer not null default 0,
    failure_count       integer not null default 0,
    validation_count    integer not null default 0,
    schema_version      integer,
    stored_fingerprint  text,
    current_fingerprint text,
    fingerprint_match   boolean,
    message             text,
    locator_results     jsonb not null default '[]'::jsonb
);

create index if not exists validation_runs_route_idx
on public.validation_runs (site_id, route_id, task_id, variant_key, validated_at desc);

create index if not exists validation_runs_playbook_idx
on public.validation_runs (playbook_id, validated_at desc);

-- ── benchmark_runs ────────────────────────────────────────────────────────
create table if not exists public.benchmark_runs (
    id              bigint generated by default as identity primary key,
    suite_name      text not null,
    run_at          timestamptz not null default timezone('utc', now()),
    workflow_count  integer not null default 0,
    healthy_count   integer not null default 0,
    degraded_count  integer not null default 0,
    failed_count    integer not null default 0,
    warm_hit_rate   double precision,
    payload         jsonb not null default '[]'::jsonb,
    metadata        jsonb not null default '{}'::jsonb
);

create index if not exists benchmark_runs_suite_idx
on public.benchmark_runs (suite_name, run_at desc);

-- ── review_events ─────────────────────────────────────────────────────────
create table if not exists public.review_events (
    id              bigint generated by default as identity primary key,
    playbook_id     text,
    occurred_at     timestamptz not null default timezone('utc', now()),
    site            text,
    url             text,
    route_key       text,
    variant_key     text,
    tenant_id       text,
    registry_scope  text,
    reviewer        text,
    reviewer_role   text,
    action          text,   -- approved | rejected | flagged
    notes           text,
    metadata        jsonb not null default '{}'::jsonb
);

create index if not exists review_events_playbook_idx
on public.review_events (playbook_id, occurred_at desc);

create index if not exists review_events_scope_idx
on public.review_events (registry_scope, occurred_at desc);
