create table if not exists public.validation_runs (
    id bigint generated by default as identity primary key,
    playbook_id uuid not null references public.playbooks(id) on delete cascade,
    site_id uuid not null references public.sites(id) on delete cascade,
    route_id uuid not null references public.page_routes(id) on delete cascade,
    task_id uuid not null references public.tasks(id) on delete cascade,
    variant_key text not null,
    validated_at timestamptz not null default timezone('utc', now()),
    status text not null,
    success_rate double precision,
    success_count integer not null default 0,
    failure_count integer not null default 0,
    validation_count integer not null default 1,
    schema_version integer,
    stored_fingerprint text,
    current_fingerprint text,
    fingerprint_match boolean,
    message text,
    locator_results jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists validation_runs_lookup_idx
on public.validation_runs (site_id, route_id, task_id, variant_key, validated_at desc);

create index if not exists validation_runs_playbook_idx
on public.validation_runs (playbook_id, validated_at desc);
