create table if not exists public.review_events (
    id bigint generated by default as identity primary key,
    playbook_id uuid not null references public.playbooks(id) on delete cascade,
    occurred_at timestamptz not null default timezone('utc', now()),
    site text,
    url text,
    route_key text,
    variant_key text,
    tenant_id text,
    registry_scope text not null default 'public',
    reviewer text not null,
    reviewer_role text not null,
    action text not null,
    notes text not null default '',
    metadata jsonb not null default '{}'::jsonb
);

create index if not exists review_events_playbook_idx
on public.review_events (playbook_id, occurred_at desc);

create index if not exists review_events_scope_idx
on public.review_events (registry_scope, occurred_at desc);
